-- First run banks table
CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(255),
    app_id VARCHAR2(255)
);

-- Then run reviews table
CREATE TABLE reviews (
    review_id VARCHAR2(64) PRIMARY KEY,
    bank_id NUMBER REFERENCES banks(bank_id),
    review_text CLOB,
    rating NUMBER,
    review_date DATE,
    sentiment VARCHAR2(20),
    theme VARCHAR2(100)
);
